# -*- coding: utf-8 -*-
"""Assignment-1(0513)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19VxfyUn5BILE9yeKqFZ_LSVuC2b7Huen
"""

numbers=[12,45,23,45,67,12]
frequency={}
for num in numbers:
  if num in frequency:
    frequency[num] += 1
  else:
    frequency[num] = 1
print("frequency of each element:")
for key in frequency:
  print(key,":",frequency[key])

numbers=[12,45,23,45,67,12]
unique=[]
for num in numbers:
  if num not in unique:
    unique.append(num)
print(unique)

integer=[12,24,36,48]
target = 60
for i in range(len(integer)):
  for j in range(i+1,len(integer)):
      if integer[i]+integer[j]==target:
          print(integer[i],integer[j])

